---
sudo: required
dist: trusty

language: python
python: "2.7"

before_install:
  - sudo apt-get update -q

install:
  - pip install ansible
  - pip install ansible-lint

  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

before_script:
  - ansible-playbook -i tests/inventory tests/travis_test.yml --syntax-check
    #  - ansible-lint tests/travis_test.yml

script:
  - ansible-playbook -i tests/inventory -c local -b tests/travis_test.yml
