---

- hosts: synapse
  become: yes
  become_user: root
  vars_files:
      - synapse_vars.yml

  tasks:
    - name: Install packages needed by synapse
      action: apt pkg={{item}} state=installed
      with_items:
       - build-essential
       - python2.7-dev
       - libffi-dev
       - python-pip
       - python-setuptools
       - sqlite3
       - libssl-dev
       - python-virtualenv
       - python3-openssl
       - libjpeg-dev

    - name: Create synapse user
      user: name={{ username }} shell=/bin/bash comment="{{ username }}"

    - name: Create virtualenv
      command: virtualenv -p python2.7 ~/.synapse
      args:
        chdir: /home/{{ username }}

    - name: PIP to upgrade setup tools
      pip: name=setuptools virtualenv=/home/{{ username }}/.synapse extra_args='--upgrade'

    - name: PIP to install needed dependencies into virtualenv
      action: pip name={{ item }} virtualenv=/home/{{ username }}/.synapse
      with_items:
       - cryptography
       - pyasn1_modules
       - characteristic
       - simplejson
       - canonicaljson

    - name: PIP to install synapse from Git Repo into virtualenv
      pip: name={{ git_repo }} virtualenv=/home/{{ username }}/.synapse

    - name: PIP rollback to ldap3 v1.4 (hotfix)
      pip: name="ldap3==1.4" virtualenv=/home/{{ username }}/.synapse

    - name: Generate homeserver.yaml config file
      shell: ". bin/activate && python -m synapse.app.homeserver --server-name {{ hostname }} --config-path homeserver.yaml --generate-config --report-stats=yes"
      args:
        chdir: /home/{{ username }}/.synapse/
        creates: /home/{{ username }}/.synapse/homeserver.yaml

    - name: Configure if registrations are enabled by default or not
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^enable_registration:"
        line: "enable_registration: {{ enable_registration }}"

    - name: Configure if captchas are enabled by default or not
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^enable_registration_captcha:"
        line: "enable_registration_captcha: {{ enable_registration_captcha }}"

    - name: Configure private-key recaptcha key
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^recaptcha_private_key:"
        line: "recaptcha_private_key: {{ recaptcha_private_key }}"

    - name: Configure public-key recaptcha key
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^recaptcha_public_key:"
        line: "recaptcha_public_key: {{ recaptcha_public_key }}"

    - name: Configure fullchain location
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^tls_certificate_path:"
        line: "tls_certificate_path: {{ absolute_path_certificate }}"

    - name: Configure fullchain location
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        regexp: "^tls_private_key_path:"
        line: "tls_private_key_path: {{ absolute_path_key }}"

    - name: Configure turn_uris
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        line: "turn_uris: [ \"turn:{{ hostname }}:3478?transport=udp\", \"turn:{{ hostname }}:3478?transport=tcp\" ]"

    - name: Configure turn_user_lifetime
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        line: "turn_shared_secret: {{ turn_shared_secret }}"

    - name: Configure turn_user_lifetime
      lineinfile: dest=/home/{{ username }}/.synapse/homeserver.yaml
      args:
        line: "turn_user_lifetime: 86400000"

    - name: Set permissions
      file:
        path='/home/{{ username }}/.synapse'
        state=directory
        owner={{ username }}
        group={{ username }}
        recurse=yes

    - name: Install systemd conf
      template:
          src=etc/systemd/system/synapse.service.j2
          dest=/etc/systemd/system/synapse.service
          mode=0644

    - name: Reloading Daemons
      command: systemctl daemon-reload

    - name: Enabling service
      command: systemctl enable synapse

    - name: Start synapse server
      service: name=synapse state=started
