---

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false

- name: install basic packages
  apt:
    name:
      - wget
      - git
    state: present

- name: Import openssl tasks
  import_tasks: openssl.yml
  when: generate_DH_params

- name: Import synapse tasks
  import_tasks: synapse.yml
  tags: synapse
- name: Import tunrserver tasks
  import_tasks: coturn.yml
  when: install_turnserver|bool == true
  tags: turnserver
- name: Import nginx tasls
  import_tasks: nginx.yml
  when: install_reverseproxy|bool == true
- name: Import postgres tasks
  import_tasks: postgres.yml
  when: install_postgres|bool == true
  tags: postgres
- name: Import mxisd tasks
  import_tasks: mxisd.yml
  when: install_mxisd|bool == true
- name: Import riot.im tasks
  import_tasks: riot.im.yml
  tags: riot
