---

- name: Update apt cache
  apt: update_cache=yes
  changed_when: false

- name: install basic packages
  apt: "pkg={{item}} state=installed"
  with_items:
    - wget
    - git

- import_tasks: openssl.yml
  when: generate_DH_params

- import_tasks: synapse.yml
  tags: synapse
- import_tasks: coturn.yml
  when: install_turnserver|bool == true
  tags: turnserver
- import_tasks: nginx.yml
  when: install_reverseproxy|bool == true
- import_tasks: postgres.yml
  when: install_postgres|bool == true
  tags: postgres
- import_tasks: mxisd.yml
  when: install_mxisd|bool == true
- import_tasks: riot.im.yml
  tags: riot
