---

- hosts: synapse

  tasks:
    - name: Install packages needed to the reverse proxy
      action: apt pkg=nginx state=installed

    - name: Install nginx conf
      template:
        src:  etc/nginx/sites-available/synapse.j2
        dest: /etc/nginx/sites-available/synapse

    - name: Enable the vhost (symlink)
      file:
        src: /etc/nginx/sites-available/synapse
        dest: /etc/nginx/sites-enabled/synapse
        state: link

    - name: Reload nginx
      service: name=nginx state=reloaded
