---

- name: Install packages required by synapse
  apt:
    name:
      - build-essential
      - python3-dev
      - libffi-dev
      - python-setuptools
      - python3-pip
      - sqlite3
      - libssl-dev
      - python3-virtualenv
      - python3-openssl
      - libjpeg-dev
      - python3-lxml
      - libxslt1-dev
      - jq
      - virtualenv
    state: present

- name: Create synapse user
  user:
    name: "{{ username }}"
    shell: /bin/bash
    comment: "{{ username }}"

- name: PIP to upgrade setuptools
  pip: 
    name: setuptools
    virtualenv: "{{ synapse_path }}"
    virtualenv_python: python3
    extra_args: '--upgrade'
  when: not ansible_check_mode

- name: PIP to install needed dependencies and synapse into virtualenv
  pip:
    name:
      - cryptography
      - pyasn1_modules
      - characteristic
      - simplejson
      - canonicaljson
      - ipaddress
      - lxml
      - jinja2 
      - bleach
      - netaddr
      - matrix-synapse
    virtualenv: "{{ synapse_path }}"
    virtualenv_python: python3
  notify:
    - restart synapse
  when: not ansible_check_mode

#- name: PIP rollback to ldap3 v1.4 (hotfix)
#  pip: name="ldap3==1.4" virtualenv="/home/{{ username }}/.synapse"

- name: Generate homeserver.yaml config file
  shell: ". bin/activate && python -m synapse.app.homeserver --server-name {{ domain }} --config-path homeserver.yaml --generate-config --report-stats=yes"
  args:
    chdir: "{{ synapse_path }}/"
    creates: "{{ synapse_path }}/homeserver.yaml"

- name: Configure homeserver.yaml template
  template:
    src: homeserver.yaml.j2
    dest: "{{ synapse_path }}/homeserver.yaml"
    mode: 0644
  notify:
    - restart synapse

- name: Creating mail template folders
  file:
    path: "{{ synapse_path }}/res/templates"
    state: directory
    mode: 0755
  when: mail

- name: Set permissions
  file:
    path: "/home/{{ username }}/.synapse"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Configure .well-known server matrix discovery
  template:
    src: server.j2
    dest: "{{ matrix_well_known_location }}/server"
    mode: 0644
  when: install_well_known

- name: Install synapse systemd conf
  template:
      src: etc/systemd/system/synapse.service.j2
      dest: /etc/systemd/system/synapse.service
      mode: 0644
  notify:
      - reload systemctl daemon
      - restart synapse