- name: reload systemctl daemon
  systemd: daemon_reload=yes
  tags: synapse, turnserver, mxisd, riot

- name: restart turn server
  service: name=turnserver state=restarted enabled=yes
  tags: turnserver

- name: restart mxisd
  service: name=mxisd state=restarted enabled=yes
  tags: mxisd

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  tags: riot

- name: restart synapse
  service: name=synapse state=started enabled=yes
  tags: synapse