- name: Reload systemctl config
  command: systemctl daemon-reload

- name: Restart turn server
  service: name=turnserver state=restarted

- name: Restart mxisd daemon
  service: name=mxisd state=restarted

- name: Reload nginx
  service: name=nginx state=reloaded
  tags: riot

- name: Restart synapse
  service: name=synapse state=started